/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agenda.frames;

import agenda.Evento;
import java.time.*;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.Cursor;

import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;

import db.SQLiteDataBase;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
/**
 *
 * @author aluno
 */
public class Calendario extends javax.swing.JFrame {
    
    private ArrayList<Evento> eventos_dia = new ArrayList();
    private int dia_aberto;
    private int evento_id = 0;
    private String db_path = "./agendas.db";
    private int agenda_id = 1;

    /**
     * Creates new form NewJFrame
     */
    public Calendario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jD_Eventos = new javax.swing.JDialog();
        lb_dia = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jL_ListaEventos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jTF_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTA_descricao = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTF_hora_inicial = new javax.swing.JFormattedTextField();
        jTF_hora_final = new javax.swing.JFormattedTextField();
        jBtn_Salvar = new javax.swing.JButton();
        jBtn_Cancelar = new javax.swing.JButton();
        jBtn_Novo = new javax.swing.JButton();
        jTF_data = new javax.swing.JFormattedTextField();
        jCB_DiaInteiro = new javax.swing.JCheckBox();
        jBtn_apagar = new javax.swing.JButton();
        lb_23 = new javax.swing.JLabel();
        lb_24 = new javax.swing.JLabel();
        lb_25 = new javax.swing.JLabel();
        lb_22 = new javax.swing.JLabel();
        lb_35 = new javax.swing.JLabel();
        lb_21 = new javax.swing.JLabel();
        lb_31 = new javax.swing.JLabel();
        lb_32 = new javax.swing.JLabel();
        lb_33 = new javax.swing.JLabel();
        lb_34 = new javax.swing.JLabel();
        lb_41 = new javax.swing.JLabel();
        lb_51 = new javax.swing.JLabel();
        lb_61 = new javax.swing.JLabel();
        lb_11 = new javax.swing.JLabel();
        lb_42 = new javax.swing.JLabel();
        lb_43 = new javax.swing.JLabel();
        lb_44 = new javax.swing.JLabel();
        lb_45 = new javax.swing.JLabel();
        lb_55 = new javax.swing.JLabel();
        lb_54 = new javax.swing.JLabel();
        lb_53 = new javax.swing.JLabel();
        lb_52 = new javax.swing.JLabel();
        lb_62 = new javax.swing.JLabel();
        lb_63 = new javax.swing.JLabel();
        lb_64 = new javax.swing.JLabel();
        lb_65 = new javax.swing.JLabel();
        lb_12 = new javax.swing.JLabel();
        lb_13 = new javax.swing.JLabel();
        lb_14 = new javax.swing.JLabel();
        lb_15 = new javax.swing.JLabel();
        lbMes = new javax.swing.JLabel();
        lb_16 = new javax.swing.JLabel();
        lb_26 = new javax.swing.JLabel();
        lb_36 = new javax.swing.JLabel();
        lb_46 = new javax.swing.JLabel();
        lb_56 = new javax.swing.JLabel();
        lb_66 = new javax.swing.JLabel();
        lb_17 = new javax.swing.JLabel();
        lb_27 = new javax.swing.JLabel();
        lb_37 = new javax.swing.JLabel();
        lb_47 = new javax.swing.JLabel();
        lb_57 = new javax.swing.JLabel();
        lb_67 = new javax.swing.JLabel();
        lb_Dom = new javax.swing.JLabel();
        lb_Seg = new javax.swing.JLabel();
        lb_Ter = new javax.swing.JLabel();
        lb_Qua = new javax.swing.JLabel();
        lb_Qui = new javax.swing.JLabel();
        lb_Sex = new javax.swing.JLabel();
        lb_Sab = new javax.swing.JLabel();
        btnMesAbaixo = new javax.swing.JButton();
        btnAnoAbaixo = new javax.swing.JButton();
        btnMesAcima = new javax.swing.JButton();
        btnAnoAcima = new javax.swing.JButton();
        lbAno = new javax.swing.JLabel();

        jD_Eventos.setTitle("Eventos");
        jD_Eventos.setAlwaysOnTop(true);
        jD_Eventos.setMaximumSize(new java.awt.Dimension(501, 475));
        jD_Eventos.setMinimumSize(new java.awt.Dimension(501, 475));
        jD_Eventos.setModal(true);
        jD_Eventos.setPreferredSize(new java.awt.Dimension(501, 475));
        jD_Eventos.setResizable(false);
        jD_Eventos.setSize(new java.awt.Dimension(501, 475));

        lb_dia.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lb_dia.setText("XX/XX/XXXX");

        jL_ListaEventos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jL_ListaEventos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jL_ListaEventos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jL_ListaEventos.setMaximumSize(new java.awt.Dimension(50, 130));
        jL_ListaEventos.setMinimumSize(new java.awt.Dimension(50, 130));
        jL_ListaEventos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jL_ListaEventosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jL_ListaEventos);

        jLabel1.setText("Evento:");

        jLabel2.setText("Descrição:");

        jTA_descricao.setColumns(20);
        jTA_descricao.setRows(5);
        jScrollPane2.setViewportView(jTA_descricao);

        jLabel3.setText("Data:");

        jLabel4.setText("Hora inicial:");

        jLabel5.setText("Hora final:");

        jTF_hora_inicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH:mm"))));

        jTF_hora_final.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH:mm"))));

        jBtn_Salvar.setText("Salvar");
        jBtn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_SalvarActionPerformed(evt);
            }
        });

        jBtn_Cancelar.setText("Cancelar");
        jBtn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_CancelarActionPerformed(evt);
            }
        });

        jBtn_Novo.setText("Novo");
        jBtn_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_NovoActionPerformed(evt);
            }
        });

        jTF_data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        jCB_DiaInteiro.setText("Dia inteiro?");
        jCB_DiaInteiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_DiaInteiroActionPerformed(evt);
            }
        });

        jBtn_apagar.setText("Apagar");
        jBtn_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_apagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jD_EventosLayout = new javax.swing.GroupLayout(jD_Eventos.getContentPane());
        jD_Eventos.getContentPane().setLayout(jD_EventosLayout);
        jD_EventosLayout.setHorizontalGroup(
            jD_EventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_EventosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jD_EventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jD_EventosLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_data, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtn_Cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtn_Salvar))
                    .addGroup(jD_EventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBtn_Novo)
                        .addGroup(jD_EventosLayout.createSequentialGroup()
                            .addGroup(jD_EventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jD_EventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                .addComponent(jTF_nome)))
                        .addComponent(jBtn_apagar))
                    .addGroup(jD_EventosLayout.createSequentialGroup()
                        .addComponent(jCB_DiaInteiro)
                        .addGap(62, 62, 62)
                        .addGroup(jD_EventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jD_EventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_hora_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_hora_final, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jD_EventosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_dia)
                .addGap(199, 199, 199))
        );
        jD_EventosLayout.setVerticalGroup(
            jD_EventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_EventosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lb_dia)
                .addGap(15, 15, 15)
                .addGroup(jD_EventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jD_EventosLayout.createSequentialGroup()
                        .addComponent(jBtn_Novo)
                        .addGap(18, 18, 18)
                        .addComponent(jBtn_apagar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addGroup(jD_EventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTF_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jD_EventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jD_EventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jTF_hora_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jD_EventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTF_hora_final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCB_DiaInteiro))
                        .addGap(28, 28, 28)
                        .addGroup(jD_EventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn_Cancelar)
                            .addComponent(jBtn_Salvar))))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda");
        setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(439, 542));
        setResizable(false);
        setSize(new java.awt.Dimension(439, 542));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lb_23.setBackground(new java.awt.Color(255, 255, 255));
        lb_23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_23MouseClicked(evt);
            }
        });

        lb_24.setBackground(new java.awt.Color(255, 255, 255));
        lb_24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_24MouseClicked(evt);
            }
        });

        lb_25.setBackground(new java.awt.Color(255, 255, 255));
        lb_25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_25MouseClicked(evt);
            }
        });

        lb_22.setBackground(new java.awt.Color(255, 255, 255));
        lb_22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_22MouseClicked(evt);
            }
        });

        lb_35.setBackground(new java.awt.Color(255, 255, 255));
        lb_35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_35MouseClicked(evt);
            }
        });

        lb_21.setBackground(new java.awt.Color(255, 255, 255));
        lb_21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_21MouseClicked(evt);
            }
        });

        lb_31.setBackground(new java.awt.Color(255, 255, 255));
        lb_31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_31MouseClicked(evt);
            }
        });

        lb_32.setBackground(new java.awt.Color(255, 255, 255));
        lb_32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_32MouseClicked(evt);
            }
        });

        lb_33.setBackground(new java.awt.Color(255, 255, 255));
        lb_33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_33MouseClicked(evt);
            }
        });

        lb_34.setBackground(new java.awt.Color(255, 255, 255));
        lb_34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_34MouseClicked(evt);
            }
        });

        lb_41.setBackground(new java.awt.Color(255, 255, 255));
        lb_41.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_41MouseClicked(evt);
            }
        });

        lb_51.setBackground(new java.awt.Color(255, 255, 255));
        lb_51.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_51MouseClicked(evt);
            }
        });

        lb_61.setBackground(new java.awt.Color(255, 255, 255));
        lb_61.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_61.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_61MouseClicked(evt);
            }
        });

        lb_11.setBackground(new java.awt.Color(255, 255, 255));
        lb_11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lb_11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_11MouseClicked(evt);
            }
        });

        lb_42.setBackground(new java.awt.Color(255, 255, 255));
        lb_42.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_42MouseClicked(evt);
            }
        });

        lb_43.setBackground(new java.awt.Color(255, 255, 255));
        lb_43.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_43MouseClicked(evt);
            }
        });

        lb_44.setBackground(new java.awt.Color(255, 255, 255));
        lb_44.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_44MouseClicked(evt);
            }
        });

        lb_45.setBackground(new java.awt.Color(255, 255, 255));
        lb_45.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_45MouseClicked(evt);
            }
        });

        lb_55.setBackground(new java.awt.Color(255, 255, 255));
        lb_55.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_55MouseClicked(evt);
            }
        });

        lb_54.setBackground(new java.awt.Color(255, 255, 255));
        lb_54.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_54MouseClicked(evt);
            }
        });

        lb_53.setBackground(new java.awt.Color(255, 255, 255));
        lb_53.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_53MouseClicked(evt);
            }
        });

        lb_52.setBackground(new java.awt.Color(255, 255, 255));
        lb_52.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_52MouseClicked(evt);
            }
        });

        lb_62.setBackground(new java.awt.Color(255, 255, 255));
        lb_62.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_62MouseClicked(evt);
            }
        });

        lb_63.setBackground(new java.awt.Color(255, 255, 255));
        lb_63.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_63.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_63MouseClicked(evt);
            }
        });

        lb_64.setBackground(new java.awt.Color(255, 255, 255));
        lb_64.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_64.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_64MouseClicked(evt);
            }
        });

        lb_65.setBackground(new java.awt.Color(255, 255, 255));
        lb_65.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_65.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_65MouseClicked(evt);
            }
        });

        lb_12.setBackground(new java.awt.Color(255, 255, 255));
        lb_12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_12MouseClicked(evt);
            }
        });

        lb_13.setBackground(new java.awt.Color(255, 255, 255));
        lb_13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_13MouseClicked(evt);
            }
        });

        lb_14.setBackground(new java.awt.Color(255, 255, 255));
        lb_14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_14MouseClicked(evt);
            }
        });

        lb_15.setBackground(new java.awt.Color(255, 255, 255));
        lb_15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_15MouseClicked(evt);
            }
        });

        lbMes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbMes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMes.setText("Mês");

        lb_16.setBackground(new java.awt.Color(255, 255, 255));
        lb_16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_16MouseClicked(evt);
            }
        });

        lb_26.setBackground(new java.awt.Color(255, 255, 255));
        lb_26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_26MouseClicked(evt);
            }
        });

        lb_36.setBackground(new java.awt.Color(255, 255, 255));
        lb_36.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_36MouseClicked(evt);
            }
        });

        lb_46.setBackground(new java.awt.Color(255, 255, 255));
        lb_46.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_46MouseClicked(evt);
            }
        });

        lb_56.setBackground(new java.awt.Color(255, 255, 255));
        lb_56.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_56MouseClicked(evt);
            }
        });

        lb_66.setBackground(new java.awt.Color(255, 255, 255));
        lb_66.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_66.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_66MouseClicked(evt);
            }
        });

        lb_17.setBackground(new java.awt.Color(255, 255, 255));
        lb_17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_17MouseClicked(evt);
            }
        });

        lb_27.setBackground(new java.awt.Color(255, 255, 255));
        lb_27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_27MouseClicked(evt);
            }
        });

        lb_37.setBackground(new java.awt.Color(255, 255, 255));
        lb_37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_37MouseClicked(evt);
            }
        });

        lb_47.setBackground(new java.awt.Color(255, 255, 255));
        lb_47.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_47MouseClicked(evt);
            }
        });

        lb_57.setBackground(new java.awt.Color(255, 255, 255));
        lb_57.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_57.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_57MouseClicked(evt);
            }
        });

        lb_67.setBackground(new java.awt.Color(255, 255, 255));
        lb_67.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_67.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_67MouseClicked(evt);
            }
        });

        lb_Dom.setBackground(new java.awt.Color(255, 255, 255));
        lb_Dom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_Dom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Dom.setText("D");

        lb_Seg.setBackground(new java.awt.Color(255, 255, 255));
        lb_Seg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_Seg.setForeground(new java.awt.Color(0, 0, 0));
        lb_Seg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Seg.setText("S");

        lb_Ter.setBackground(new java.awt.Color(255, 255, 255));
        lb_Ter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_Ter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Ter.setText("T");

        lb_Qua.setBackground(new java.awt.Color(255, 255, 255));
        lb_Qua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_Qua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Qua.setText("Q");

        lb_Qui.setBackground(new java.awt.Color(255, 255, 255));
        lb_Qui.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_Qui.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Qui.setText("Q");

        lb_Sex.setBackground(new java.awt.Color(255, 255, 255));
        lb_Sex.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_Sex.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Sex.setText("S");

        lb_Sab.setBackground(new java.awt.Color(255, 255, 255));
        lb_Sab.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_Sab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Sab.setText("S");

        btnMesAbaixo.setText("<");
        btnMesAbaixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesAbaixoActionPerformed(evt);
            }
        });

        btnAnoAbaixo.setText("<<");
        btnAnoAbaixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnoAbaixoActionPerformed(evt);
            }
        });

        btnMesAcima.setText(">");
        btnMesAcima.setDefaultCapable(false);
        btnMesAcima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesAcimaActionPerformed(evt);
            }
        });

        btnAnoAcima.setText(">>");
        btnAnoAcima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnoAcimaActionPerformed(evt);
            }
        });

        lbAno.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbAno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAno.setText("Ano");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lb_31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lb_32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lb_33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lb_34, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lb_35, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lb_11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lb_21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lb_22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lb_23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lb_24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lb_25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lb_12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lb_13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lb_14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lb_15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_51, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_41, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lb_52, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lb_53, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lb_54, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lb_55, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lb_42, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lb_43, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lb_44, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lb_45, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_61, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_62, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_63, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_64, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_65, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_66, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lb_36, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lb_56, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_46, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_67, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lb_37, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lb_57, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_47, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lb_Seg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_Ter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_Qua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_Qui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_Sex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_Sab, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMesAbaixo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAnoAbaixo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbAno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbMes, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                                .addGap(8, 8, 8)
                                .addComponent(btnAnoAcima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMesAcima, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_Dom, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbAno, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMesAbaixo)
                    .addComponent(btnAnoAbaixo)
                    .addComponent(btnMesAcima)
                    .addComponent(btnAnoAcima))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_Sex, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_Dom, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_Sab, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_Qui, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_Seg, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_Ter, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_Qua, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_37, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_47, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_57, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_67, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_36, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_46, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_56, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_66, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lb_23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lb_35, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_34, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_41, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_51, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lb_43, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_44, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_45, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_42, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lb_55, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_52, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_53, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_54, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_61, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_65, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_62, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_63, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_64, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void atualizaCalendario(int mes, int ano){
        
        LocalDate hoje = LocalDate.now();
        
        if (mes==13){
            mes = 1;
            ano += 1;
        } else if (mes==0){
            mes = 12;
            ano -= 1;
        }
        
        int primeiro_dia = LocalDate.of(ano, mes, 1).getDayOfWeek().getValue();
        int ultimo_dia = LocalDate.of(ano, mes, 1).lengthOfMonth();
        
        String[] meses = {"Janeiro", "Fevereiro", "Março", "Abril",
                            "Maio", "Junho","Julho","Agosto",
                            "Setembro","Outubro", "Novembro", "Dezembro"};
        
        javax.swing.JLabel[][] lb_dias = {
                {lb_11, lb_12, lb_13, lb_14, lb_15, lb_16, lb_17,},
                {lb_21, lb_22, lb_23, lb_24, lb_25, lb_26, lb_27},
                {lb_31, lb_32, lb_33, lb_34, lb_35, lb_36, lb_37},
                {lb_41, lb_42, lb_43, lb_44, lb_45, lb_46, lb_47},
                {lb_51, lb_52, lb_53, lb_54, lb_55, lb_56, lb_57},
                {lb_61, lb_62, lb_63, lb_64, lb_65, lb_66, lb_67}};
        
        lbAno.setText(Integer.toString(ano));
        lbMes.setText(meses[mes-1]);
        
        Border empty_border = BorderFactory.createEmptyBorder();
        Border black_border = BorderFactory.createLineBorder(Color.black);
        Border red_border = BorderFactory.createLineBorder(Color.red, 3);
        
        Cursor hand_cursor = new Cursor(Cursor.HAND_CURSOR);
        Cursor default_cursor = new Cursor(Cursor.DEFAULT_CURSOR);
        
        SQLiteDataBase DB = new SQLiteDataBase();

        String data;
        String s_dia;
        int eventos_dia;
        int dia = 1;
        for(int i=0;i<=5; i++){
            for(int j=0;j<=6; j++){
                
                s_dia = Integer.toString(dia);
                if (s_dia.length()<2){ s_dia = "0"+s_dia; }
                
                data = Integer.toString(ano) + "-" + Integer.toString(mes) + "-" + s_dia;
                eventos_dia = DB.getEventosData(this.db_path, this.agenda_id, data).size();
                
                lb_dias[i][j].setBorder(empty_border);
                lb_dias[i][j].setText("");
                lb_dias[i][j].setCursor(default_cursor);
                lb_dias[i][j].setForeground(Color.black);
                
                if(i==0 && j>=(primeiro_dia-1)){
                    lb_dias[i][j].setText(Integer.toString(dia));
                    lb_dias[i][j].setCursor(hand_cursor);
                    if (LocalDate.of(ano, mes, dia).equals(hoje)){
                        lb_dias[i][j].setBorder(red_border);
                    } else {
                        lb_dias[i][j].setBorder(black_border);
                    }
                    if (eventos_dia>0){
                        lb_dias[i][j].setForeground(Color.blue);
                    }
                    dia++;
                } else if(i>0 && dia<=ultimo_dia){
                    lb_dias[i][j].setText(Integer.toString(dia));
                    lb_dias[i][j].setCursor(hand_cursor);
                    if (LocalDate.of(ano, mes, dia).equals(hoje)){
                        lb_dias[i][j].setBorder(red_border);
                    } else {
                        lb_dias[i][j].setBorder(black_border);
                    }
                    if (eventos_dia>0){
                        lb_dias[i][j].setForeground(Color.blue);
                    }
                    dia++;
                }
            }
        }
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        LocalDate hoje = LocalDate.now();
        int mes = hoje.getMonthValue();
        int ano = hoje.getYear();
        
        atualizaCalendario(mes, ano);
        
    }//GEN-LAST:event_formWindowOpened

    private int getMes(){
        
        String S_mes = lbMes.getText();
        
        int mes = 0;
        
        switch (S_mes){
            case "Janeiro": 
                mes = 1;
                break;
            
            case "Fevereiro": 
                mes = 2;
                break;
            
            case "Março": 
                mes = 3;
                break;
                
            case "Abril": 
                mes = 4;
                break;
                   
            case "Maio": 
                mes = 5;
                break;
                
            case "Junho": 
                mes = 6;
                break;
                
            case "Julho": 
                mes = 7;
                break;
                
            case "Agosto": 
                mes = 8;
                break;
                
            case "Setembro": 
                mes = 9;
                break;
                
            case "Outubro": 
                mes = 10;
                break;
            
            case "Novembro": 
                mes = 11;
                break;
                
            case "Dezembro": 
                mes = 12;
                break;
        }
        return mes;
    }
    
    private int getAno(){
        return Integer.parseInt(lbAno.getText());
    }
    
    private void loadEventosDialog(int dia){
        
        int ano = this.getAno();
        int mes = this.getMes();
        
        String s_dia = Integer.toString(dia);
        if (dia<10){ s_dia = "0" + s_dia; }
        
        String data_completa = s_dia + "/" + mes + "/" + ano;
        String titulo = "Eventos - " + s_dia + "/" + mes + "/" + ano;
        lb_dia.setText(data_completa);
        jD_Eventos.setTitle(titulo);
        
        String data = ano + "-" + mes + "-" + s_dia;

        SQLiteDataBase DataBase = new SQLiteDataBase();
        if (!this.eventos_dia.isEmpty()){ this.eventos_dia.clear();}
        this.eventos_dia = DataBase.getEventosData(this.db_path, this.agenda_id, data);
        
        DefaultListModel listModelHorarios = new DefaultListModel();
        String h;
       
        listModelHorarios.clear();
        jL_ListaEventos.setModel(listModelHorarios);
        if (this.eventos_dia.size()>0){
            for (int i=0; i<this.eventos_dia.size(); i++){
                h = this.eventos_dia.get(i).getHoraInicial() + " - " + this.eventos_dia.get(i).getHoraFinal();
                listModelHorarios.add(i, h);
            }
            jL_ListaEventos.setModel(listModelHorarios);
        }
        
        jD_Eventos.setVisible(true);
    }
    
    private void btnMesAcimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesAcimaActionPerformed
        // TODO add your handling code here:
        
        int ano = this.getAno();
        int mes = this.getMes() + 1;
        atualizaCalendario(mes, ano);
    }//GEN-LAST:event_btnMesAcimaActionPerformed

    private void btnAnoAcimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnoAcimaActionPerformed
        // TODO add your handling code here:
        
        int ano = this.getAno() + 1;
        int mes = this.getMes();
        atualizaCalendario(mes,ano);
    }//GEN-LAST:event_btnAnoAcimaActionPerformed

    private void btnAnoAbaixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnoAbaixoActionPerformed
        // TODO add your handling code here:
        int ano = this.getAno() -1;
        int mes = this.getMes();
        atualizaCalendario(mes, ano);
    }//GEN-LAST:event_btnAnoAbaixoActionPerformed

    private void btnMesAbaixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesAbaixoActionPerformed
        // TODO add your handling code here:
        int ano = this.getAno();
        int mes = this.getMes() - 1;
        atualizaCalendario(mes, ano);
    }//GEN-LAST:event_btnMesAbaixoActionPerformed

    private void lb_11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_11MouseClicked
        // TODO add your handling code here:
        if (!lb_11.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_11.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_11MouseClicked

    private void lb_21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_21MouseClicked
        // TODO add your handling code here:
        if (!lb_21.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_21.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_21MouseClicked

    private void jL_ListaEventosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jL_ListaEventosValueChanged
        // TODO add your handling code here:
        int index;
        if (!evt.getValueIsAdjusting() && !jL_ListaEventos.isSelectionEmpty()){
            index = jL_ListaEventos.getSelectedIndex();
            
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            
            this.evento_id = this.eventos_dia.get(index).getId();
            jTF_nome.setText(this.eventos_dia.get(index).getNome());
            jTA_descricao.setText(this.eventos_dia.get(index).getDescricao());
            jTF_data.setText(this.eventos_dia.get(index).getData().format(formatter));
            jTF_hora_inicial.setText(this.eventos_dia.get(index).getHoraInicial().toString());
            jTF_hora_final.setText(this.eventos_dia.get(index).getHoraFinal().toString());
            jCB_DiaInteiro.setSelected(this.eventos_dia.get(index).getDiaInteiro());
        }
    }//GEN-LAST:event_jL_ListaEventosValueChanged

    private void jBtn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_CancelarActionPerformed
        // TODO add your handling code here:
        
        this.evento_id = 0;
        jTF_nome.setText("");
        jTA_descricao.setText("");
        jTF_data.setText("");
        jTF_hora_inicial.setText("");
        jTF_hora_final.setText("");
        jCB_DiaInteiro.setSelected(false);
        jD_Eventos.setVisible(false);
    }//GEN-LAST:event_jBtn_CancelarActionPerformed

    private void jBtn_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_NovoActionPerformed
        // TODO add your handling code here:
        this.evento_id = 0;
        jTF_nome.setText("");
        jTA_descricao.setText("");
        jTF_data.setText(lb_dia.getText());
        jTF_hora_inicial.setText("");
        jTF_hora_final.setText("");
        jCB_DiaInteiro.setSelected(false);
        
        jL_ListaEventos.clearSelection();
    }//GEN-LAST:event_jBtn_NovoActionPerformed

    private void jCB_DiaInteiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_DiaInteiroActionPerformed
        // TODO add your handling code here:
        if(jCB_DiaInteiro.isSelected()){
            jTF_hora_inicial.setText("00:00");
            jTF_hora_inicial.setEditable(false);
            jTF_hora_final.setText("23:59");
            jTF_hora_final.setEditable(false);
        } else if(!jCB_DiaInteiro.isSelected()){
            jTF_hora_inicial.setText("");
            jTF_hora_inicial.setEditable(true);
            jTF_hora_final.setText("");
            jTF_hora_final.setEditable(true);
        }
    }//GEN-LAST:event_jCB_DiaInteiroActionPerformed

    private void jBtn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_SalvarActionPerformed
        // TODO add your handling code here:
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        
        String nome = jTF_nome.getText();
        String descricao = jTA_descricao.getText();
        String data = LocalDate.parse(jTF_data.getText(), formatter).toString();
        String hora = jTF_hora_inicial.getText();
        String hora_final = jTF_hora_final.getText();
        boolean dia_inteiro = jCB_DiaInteiro.isSelected();
        try {
            Evento novo_evento = new Evento(this.evento_id, nome, descricao, dia_inteiro, data, hora, hora_final);
            SQLiteDataBase DB = new SQLiteDataBase();
            DB.saveEvento(this.db_path, novo_evento, this.agenda_id);
            
            this.loadEventosDialog(this.dia_aberto);
            
            this.evento_id=0;
            jTF_nome.setText("");
            jTA_descricao.setText("");
            jTF_data.setText("");
            jTF_hora_inicial.setText("");
            jTF_hora_final.setText("");
            jCB_DiaInteiro.setSelected(false);
        } catch (Exception erro_message){
            JOptionPane.showMessageDialog(this, erro_message, "Erro",
                                            JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtn_SalvarActionPerformed

    private void jBtn_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_apagarActionPerformed
        // TODO add your handling code here:
        if(this.evento_id!=0){
            Object[] opc = { "CONFIRMAR", "Cancelar" };
            int resposta = JOptionPane.showOptionDialog(this, "Tem certeza que "
                    + "deseja apagar o evento " + jTF_nome.getText() + "?", 
                    "Apagar evento", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, opc, opc[0]);
            if(resposta==0){
                 try {
                    SQLiteDataBase DB = new SQLiteDataBase();
                    DB.deleteEvento(this.db_path, this.evento_id);
                    this.loadEventosDialog(this.dia_aberto);
                    this.evento_id=0;
                    jTF_nome.setText("");
                    jTA_descricao.setText("");
                    jTF_data.setText("");
                    jTF_hora_inicial.setText("");
                    jTF_hora_final.setText("");
                    jCB_DiaInteiro.setSelected(false);
                } catch (Exception erro_message){
                    JOptionPane.showMessageDialog(this, erro_message, "Erro",
                                                    JOptionPane.ERROR_MESSAGE);
                }   
            }
            
        }
    }//GEN-LAST:event_jBtn_apagarActionPerformed

    private void lb_12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_12MouseClicked
        // TODO add your handling code here:
        if (!lb_12.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_12.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_12MouseClicked

    private void lb_13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_13MouseClicked
        // TODO add your handling code here:
        if (!lb_13.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_13.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_13MouseClicked

    private void lb_14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_14MouseClicked
        // TODO add your handling code here:
        if (!lb_14.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_14.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_14MouseClicked

    private void lb_15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_15MouseClicked
        // TODO add your handling code here:
        if (!lb_15.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_15.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_15MouseClicked

    private void lb_16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_16MouseClicked
        // TODO add your handling code here:
        if (!lb_16.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_16.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_16MouseClicked

    private void lb_17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_17MouseClicked
        // TODO add your handling code here:
        if (!lb_17.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_17.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_17MouseClicked

    private void lb_22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_22MouseClicked
        // TODO add your handling code here:
        if (!lb_22.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_22.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_22MouseClicked

    private void lb_23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_23MouseClicked
        // TODO add your handling code here:
        if (!lb_23.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_23.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_23MouseClicked

    private void lb_24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_24MouseClicked
        // TODO add your handling code here:
        if (!lb_24.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_24.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_24MouseClicked

    private void lb_25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_25MouseClicked
        // TODO add your handling code here:
        if (!lb_25.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_25.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_25MouseClicked

    private void lb_26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_26MouseClicked
        // TODO add your handling code here:
        if (!lb_26.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_26.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_26MouseClicked

    private void lb_27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_27MouseClicked
        // TODO add your handling code here:
        if (!lb_27.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_27.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_27MouseClicked

    private void lb_31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_31MouseClicked
        // TODO add your handling code here:
        if (!lb_31.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_31.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_31MouseClicked

    private void lb_32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_32MouseClicked
        // TODO add your handling code here:
        if (!lb_32.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_32.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_32MouseClicked

    private void lb_33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_33MouseClicked
        // TODO add your handling code here:
        if (!lb_33.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_33.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_33MouseClicked

    private void lb_34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_34MouseClicked
        // TODO add your handling code here:
        if (!lb_34.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_34.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_34MouseClicked

    private void lb_35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_35MouseClicked
        // TODO add your handling code here:
        if (!lb_35.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_35.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_35MouseClicked

    private void lb_36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_36MouseClicked
        // TODO add your handling code here:
        if (!lb_36.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_36.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_36MouseClicked

    private void lb_37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_37MouseClicked
        // TODO add your handling code here:
        if (!lb_37.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_37.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_37MouseClicked

    private void lb_41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_41MouseClicked
        // TODO add your handling code here:
        if (!lb_41.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_41.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_41MouseClicked

    private void lb_42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_42MouseClicked
        // TODO add your handling code here:
        if (!lb_42.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_42.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_42MouseClicked

    private void lb_43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_43MouseClicked
        // TODO add your handling code here:
        if (!lb_43.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_43.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_43MouseClicked

    private void lb_44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_44MouseClicked
        // TODO add your handling code here:
        if (!lb_44.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_44.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_44MouseClicked

    private void lb_45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_45MouseClicked
        // TODO add your handling code here:
        if (!lb_45.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_45.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_45MouseClicked

    private void lb_46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_46MouseClicked
        // TODO add your handling code here:
        if (!lb_46.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_46.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_46MouseClicked

    private void lb_47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_47MouseClicked
        // TODO add your handling code here:
        if (!lb_47.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_47.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_47MouseClicked

    private void lb_51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_51MouseClicked
        // TODO add your handling code here:
        if (!lb_51.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_51.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_51MouseClicked

    private void lb_52MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_52MouseClicked
        // TODO add your handling code here:
        if (!lb_52.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_52.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_52MouseClicked

    private void lb_53MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_53MouseClicked
        // TODO add your handling code here:
        if (!lb_53.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_53.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_53MouseClicked

    private void lb_54MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_54MouseClicked
        // TODO add your handling code here:
        if (!lb_54.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_54.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_54MouseClicked

    private void lb_55MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_55MouseClicked
        // TODO add your handling code here:
        if (!lb_55.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_55.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_55MouseClicked

    private void lb_56MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_56MouseClicked
        // TODO add your handling code here:
        if (!lb_56.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_56.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_56MouseClicked

    private void lb_57MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_57MouseClicked
        // TODO add your handling code here:
        if (!lb_57.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_57.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_57MouseClicked

    private void lb_61MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_61MouseClicked
        // TODO add your handling code here:
        if (!lb_61.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_61.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_61MouseClicked

    private void lb_62MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_62MouseClicked
        // TODO add your handling code here:
        if (!lb_62.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_62.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_62MouseClicked

    private void lb_63MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_63MouseClicked
        // TODO add your handling code here:
        if (!lb_63.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_63.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_63MouseClicked

    private void lb_64MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_64MouseClicked
        // TODO add your handling code here:
        if (!lb_64.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_64.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_64MouseClicked

    private void lb_65MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_65MouseClicked
        // TODO add your handling code here:
        if (!lb_65.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_65.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_65MouseClicked

    private void lb_66MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_66MouseClicked
        // TODO add your handling code here:
        if (!lb_66.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_66.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_66MouseClicked

    private void lb_67MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_67MouseClicked
        // TODO add your handling code here:
        if (!lb_67.getText().equals("")){
            this.dia_aberto = Integer.parseInt(lb_67.getText());
            this.loadEventosDialog(this.dia_aberto);
        }
    }//GEN-LAST:event_lb_67MouseClicked

    
//listSelectionModel = jL_ListaEventos.getSelectionModel();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnoAbaixo;
    private javax.swing.JButton btnAnoAcima;
    private javax.swing.JButton btnMesAbaixo;
    private javax.swing.JButton btnMesAcima;
    private javax.swing.JButton jBtn_Cancelar;
    private javax.swing.JButton jBtn_Novo;
    private javax.swing.JButton jBtn_Salvar;
    private javax.swing.JButton jBtn_apagar;
    private javax.swing.JCheckBox jCB_DiaInteiro;
    private javax.swing.JDialog jD_Eventos;
    private javax.swing.JList<String> jL_ListaEventos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTA_descricao;
    private javax.swing.JFormattedTextField jTF_data;
    private javax.swing.JFormattedTextField jTF_hora_final;
    private javax.swing.JFormattedTextField jTF_hora_inicial;
    private javax.swing.JTextField jTF_nome;
    private javax.swing.JLabel lbAno;
    private javax.swing.JLabel lbMes;
    private javax.swing.JLabel lb_11;
    private javax.swing.JLabel lb_12;
    private javax.swing.JLabel lb_13;
    private javax.swing.JLabel lb_14;
    private javax.swing.JLabel lb_15;
    private javax.swing.JLabel lb_16;
    private javax.swing.JLabel lb_17;
    private javax.swing.JLabel lb_21;
    private javax.swing.JLabel lb_22;
    private javax.swing.JLabel lb_23;
    private javax.swing.JLabel lb_24;
    private javax.swing.JLabel lb_25;
    private javax.swing.JLabel lb_26;
    private javax.swing.JLabel lb_27;
    private javax.swing.JLabel lb_31;
    private javax.swing.JLabel lb_32;
    private javax.swing.JLabel lb_33;
    private javax.swing.JLabel lb_34;
    private javax.swing.JLabel lb_35;
    private javax.swing.JLabel lb_36;
    private javax.swing.JLabel lb_37;
    private javax.swing.JLabel lb_41;
    private javax.swing.JLabel lb_42;
    private javax.swing.JLabel lb_43;
    private javax.swing.JLabel lb_44;
    private javax.swing.JLabel lb_45;
    private javax.swing.JLabel lb_46;
    private javax.swing.JLabel lb_47;
    private javax.swing.JLabel lb_51;
    private javax.swing.JLabel lb_52;
    private javax.swing.JLabel lb_53;
    private javax.swing.JLabel lb_54;
    private javax.swing.JLabel lb_55;
    private javax.swing.JLabel lb_56;
    private javax.swing.JLabel lb_57;
    private javax.swing.JLabel lb_61;
    private javax.swing.JLabel lb_62;
    private javax.swing.JLabel lb_63;
    private javax.swing.JLabel lb_64;
    private javax.swing.JLabel lb_65;
    private javax.swing.JLabel lb_66;
    private javax.swing.JLabel lb_67;
    private javax.swing.JLabel lb_Dom;
    private javax.swing.JLabel lb_Qua;
    private javax.swing.JLabel lb_Qui;
    private javax.swing.JLabel lb_Sab;
    private javax.swing.JLabel lb_Seg;
    private javax.swing.JLabel lb_Sex;
    private javax.swing.JLabel lb_Ter;
    private javax.swing.JLabel lb_dia;
    // End of variables declaration//GEN-END:variables
}
